variable: [hus, psl, siconc, ta, tas, tos, ua, uas, va, vas, wap, zg] # options: [hus, psl, siconc, ta, tas, tos, ua, uas, va, vas, wap, zg] (one or multiple)
# if more than 1 variable is selected that contain pressure levels, plev selection will be applied to all
plev: [5000, 10000, 15000, 20000, 25000, 30000, 40000, 50000, 60000, 70000, 85000, 92500, 100000] # options: null, [5000, 10000, 15000, 20000, 25000, 30000, 40000, 50000, 60000, 70000, 85000, 92500, 100000] (Pa, but code also understands inputs in hPa)
freq: monthly  # options: monthly or daily (for daily: ERA5 ref data is currently still missing)
grid: gn # only supports gn
models: ["free_run_control", "free_run_prediction", "forced_sst", "forced_sst_2k", "forced_sst_4k", "archesweather"] # options: ["free_run_control", "free_run_prediction", "forced_sst", "forced_sst_2k", "forced_sst_4k", "archesweather"]
time:
  use_named: null # options: TRP (training period) or TSTP (testing period) or null and set manually
  start: "1979-01-01"
  end: "2024-12-31"

mode: anomaly # options: anomaly (default), detrend, both (first detrend, then anomaly) 
anom_baseline:
  start: "1981-01-01"
  end: "2010-12-31"
detrend:
  preserve_mean: true # true = remove only slope, false = remove full fitted trend
detr_baseline:
  start: "1981-01-01" # options: "yyyy-mm-dd" or null (=entire period of data)
  end: "2010-12-31"

figsize: [11.5, 4.8]
title: null # e.g. "Global Annual Mean {long_name} Anomaly ({var})"

ticks:
  major: 5
  minor: 1

legend:
  loc: "lower right"
  inside_plot: false

special_outdir: null # options: string after outputs/anomalies or null

# colour-blind / red-green blind friendly colours (Okabe-Ito colour palette)
colours:
  base_colours:
    forced_sst:      "#0072B2"  # blue
    forced_sst_2k:   "#E69F00"  # orange
    forced_sst_4k:   "#009E73"  # green
    free_run_control: "#D55E00"  # vermillion
    free_run_prediction: "#4D4D4D"  # neutral dark grey
    archesweather:     "#CC79A7"  # purple

  colours_light:
    forced_sst:      "#56B4E9"
    forced_sst_2k:   "#F0E442"
    forced_sst_4k:   "#7ED1B2"
    free_run_control: "#F4A582"
    free_run_prediction: "#BDBDBD" 
    archesweather:    "#E7B7D4"   


