variable: [hus] # options: [hus, psl, siconc, ta, tas, tos, ua, uas, va, vas, wap, zg] (one or multiple)
# if more than 1 variable is selected that contain pressure levels, plev selection will be applied to all
plev: [700] # options: null, [5000, 10000, 15000, 20000, 25000, 30000, 40000, 50000, 60000, 70000, 85000, 92500, 100000] (Pa, but code also understands inputs in hPa)
freq: monthly # options: monthly or daily (for daily: ERA5 ref data is currently still missing)
grid: gn # only supports gn
models: ["free_run_control", "free_run_prediction", "forced_sst", "forced_sst_2k", "forced_sst_4k", "archesweather"] # options: ["free_run_control", "free_run_prediction", "forced_sst", "forced_sst_2k", "forced_sst_4k", "archesweather"]
map_era5: true # only works for method map; will create same maps for era5; needs at least one model set in models (bug to fix later)
time:
  use_named: null # options: TRP (training period) or TSTP (testing period) or null and set manually
  start: "1979-01-01"
  end: "2024-12-31"

# calc basics
method: map # options: timeseries, map
time_stat: trend # options: raw (will be monthy or daily, depeding on "freq"), annual_mean, trend (for timeseries this means annual_mean + trend per decade; for map this means just trend per decade)
detrend: # does not work in combination with time_stat: trend 
  enabled: false   
  preserve_mean: true # set to true if method = map, otherwise colours will be off
  base_period: total # options: total or unique (if unique, please set start and end)
  # only relevant for base_period: unique, otherwise ignored
  base_start: "1979-01-01"
  base_end: "1999-12-31"
difference: true # will calc and plot the difference Model - ERA5
anomaly: false # will subtract the baseline specified below from the data
baseline: # will only become relevant if anomaly=true
  start: "1979-01-01"
  end: "1983-12-31"
include_ensemble_mean_as_member: true
only_mean: true # if this is set to true, include_ensemble_mean_as_member also has to be true

# map basics
location: global # options: arctic, antarctic, individual, global (=null)
global_centre: 0 # only relevant if location=global, longitude that is in centre (0≈Africa, 180≈pacific ocean)
individual: # will only become relevant if location=individual
  # UPPER LEFT corner of bounding box
  lat0: 38.34 # [90, -90]
  lon0: -27.77 # [-180, 180] or [0, 360], code understands both
  # LOWER RIGHT corner of bounding box
  lat1: -40.09
  lon1: 68.55
  point_pad_deg: 2.0
polar:
  min_latitude: 60.0   # used for arctic
  max_latitude: -60.0  # used for antarctic

# plotting settings
title: null # e.g. ... ; title may contain {var}, {long_name}, {model}, {proper_model_name}, {member}, {plev}, {plev_hpa}, {method}, {start}, {end}, {time_label} 
coastline_colour: black

colourbar: 
  use_custom_bins: true # if false: the following params don't matter and 21 levels will be used for plotting, which may lead to uncommon ticks; if true: uses settings below
  bin_size: null # null or int; if null (recommended), a function (nice_bin_size()) will determine the best bins depending on the passed desired number of bins
  target_bins: 20 # only used if bin_size is null
  tick_every: 2 # ticks at every x-th value
  include_zero_tick: true # whether to set a tick at 0
  mode: auto # options: centered (white at 0), linear (for absolute fields), auto (will automatically choose "centered" for diff or anomaly plots if vmin <= 0 <= vmax, otherwise "linear")
  manual_vmin: null # if set, they will overwrite everything; options: null or float
  manual_vmax: null # options: null or float

colour_scheme: BrBG #Spectral_r # case-sensitive! works best for diverging colourmaps, as we force a white bin around zero
figsize: null # if null then automatically [9,5] for global map, [8,8] for (ant-)arctic map, [12,4] for timeseries 
ylabel: null
xlabel: null
legend_loc: lower right # options: 'upper left', 'upper right', 'lower left', 'lower right' , 'upper center', 'lower center', 'center left', 'center right', 'center', 'right', 'best'

# colour-blind / red-green blind friendly colours (Okabe-Ito colour palette)
colours:
  base_colours:
    forced_sst:      "#0072B2"  # blue
    forced_sst_2k:   "#E69F00"  # orange
    forced_sst_4k:   "#009E73"  # green
    free_run_control: "#D55E00"  # vermillion
    free_run_prediction: "#4D4D4D"  # neutral dark grey
    archesweather:     "#CC79A7"  # purple

  colours_light:
    forced_sst:      "#56B4E9"
    forced_sst_2k:   "#F0E442"
    forced_sst_4k:   "#7ED1B2"
    free_run_control: "#F4A582"
    free_run_prediction: "#BDBDBD" 
    archesweather:    "#E7B7D4"   

special_outdir: null # options: string after outputs/individual_plots/{method}/{var} or null

range_source:
  suffix: "_ALL"
  csv_file1: "outputs/range_summary/range_summary_compact${.suffix}.csv"
  csv_file2: "outputs/range_summary/model_minus_era5_summary_by_var_plev${.suffix}.csv"
  percentile: 99 # options: 99, 95, raw; impacts the selection of the min/max values of the colourbar (e.g. 95 uses the 5th and 95th percentile and therefore includes less extremes than option 99 or even less then option "raw")
