variable: [tas] # options: [hus, psl, siconc, ta, tas, tos, ua, uas, va, vas, wap, zg] (one or multiple)
# if more than 1 variable is selected that contain pressure levels, plev selection will be applied to all
plev: [5000, 10000, 15000, 20000, 25000, 30000, 40000, 50000, 60000, 70000, 85000, 92500, 100000] # options: null, [5000, 10000, 15000, 20000, 25000, 30000, 40000, 50000, 60000, 70000, 85000, 92500, 100000] (Pa, but code also understands inputs in hPa)
freq: daily # only daily!
grid: gn # only supports gn
models: ["free_run_control", "free_run_prediction", "forced_sst", "forced_sst_2k", "forced_sst_4k", "archesweather"] # options: ["free_run_control", "free_run_prediction", "forced_sst", "forced_sst_2k", "forced_sst_4k", "archesweather"]

time:
  use_named: null # options: TRP (training period) or TSTP (testing period) or null and set manually
  start: "1979-01-01"
  end: "2024-12-31"
season: full # options: full (entire year), DJF, MAM, JJA, SON

region: nothern # options: nothern (hemisphere), southern, global, artic, antarctic, tropics, or individual
individual: # will only become relevant if region=individual
  # UPPER LEFT corner of bounding box
  lat0: 38.34 # [90, -90]
  lon0: -27.77 # [-180, 180] or [0, 360], code understands both
  # LOWER RIGHT corner of bounding box
  lat1: -40.09
  lon1: 68.55
  point_pad_deg: 2.0
polar:
  min_latitude: 60.0   # used for arctic
  max_latitude: -60.0  # used for antarctic

include_ensemble_mean_as_member: true
only_mean: false # if this is set to true, include_ensemble_mean_as_member also has to be true

figsize: [11, 5]
title: null

ticks:
  major: 1
  minor: 1

legend:
  loc: "lower right"
  inside_plot: false

special_outdir: null # options: string after outputs/global_mean or null

# colour-blind / red-green blind friendly colours (Okabe-Ito colour palette)
colours:
  base_colours:
    forced_sst:      "#0072B2"  # blue
    forced_sst_2k:   "#E69F00"  # orange
    forced_sst_4k:   "#009E73"  # green
    free_run_control: "#D55E00"  # vermillion
    free_run_prediction: "#4D4D4D"  # neutral dark grey
    archesweather:     "#CC79A7"  # purple

  colours_light:
    forced_sst:      "#56B4E9"
    forced_sst_2k:   "#F0E442"
    forced_sst_4k:   "#7ED1B2"
    free_run_control: "#F4A582"
    free_run_prediction: "#BDBDBD" 
    archesweather:    "#E7B7D4"