variable: psl # only works with psl! Do not change
freq: monthly # options: monthly or daily (for daily: ERA5 ref data is currently still missing)
grid: gn # only supports gn
models: ["free_run_control", "free_run_prediction", "forced_sst", "forced_sst_2k", "forced_sst_4k"] # options: ["free_run_control", "free_run_prediction", "forced_sst", "forced_sst_2k", "forced_sst_4k"]

time:
  use_named: null # options: TRP (training period) or TSTP (testing period) or null and set manually
  start: "1979-01-01"
  end: "2024-12-31"

baseline:
  start: "1981-01-01"
  end: "2010-12-31"

bar_width_days: 25
figsize: [18, 4]

include_ensemble_mean_as_member: true 
only_mean: false # if this is set to true, include_ensemble_mean_as_member also has to be true

enso_plot:
  colour_elnino: "steelblue"
  colour_lanina: "indianred"

hist_kde:
  enabled: true
  hist_bins: 30 # amount of bins for histograms
  hist_pad: 0.5 # padding after tails
  kde_n_eval: 200 
  kde_bw_method: scott
  xpad: 0.02 # padding underneath bottom of histogram (to not sit immediately on y-axis)
  model_colour: "steelblue"
  model_linecol: "steelblue"
  era5_colour: "gold"
  era5_linecol: "black"

regions:
  # Tahiti: 15–20°S, 145–155°W -> 360 - 145 = 215
  # Darwin: 10–15°S, 125–135°E 
  tahiti: {lat0: -15, lat1: -20, lon0: 205, lon1: 215}
  darwin: {lat0: -10, lat1: -15, lon0: 125, lon1: 135}

special_outdir: null # options: string after outputs/soi or null