variable: [hus, psl, siconc, ta, tas, tos, ua, uas, va, vas, wap, zg] # options: [hus, psl, siconc, ta, tas, tos, ua, uas, va, vas, wap, zg] (one or multiple)
# if more than 1 variable is selected that contain pressure levels, plev selection will be applied to all
plev: [5000, 10000, 15000, 20000, 25000, 30000, 40000, 50000, 60000, 70000, 85000, 92500, 100000] # options: null, [5000, 10000, 15000, 20000, 25000, 30000, 40000, 50000, 60000, 70000, 85000, 92500, 100000] (Pa, but code also understands inputs in hPa)
freq: daily # options: monthly or dailys
grid: gn # only supports gn
models: ["forced_sst"] # one model per figure usually makes most sense here; options: ["free_run_control", "free_run_prediction", "forced_sst", "forced_sst_2k", "forced_sst_4k", "archesweather"]

time:
  use_named: null  # options: TRP (training period) or TSTP (testing period) or null and set manually
  start: "1979-01-01"
  end: "2024-12-31"
season: full  # options: full (entire year), DJF, MAM, JJA, SON

include_ensemble_mean_as_member: true
only_mean: true # if this is set to true, include_ensemble_mean_as_member also has to be true
map_era5: false 

region: global # options: nothern (hemisphere), southern, global, artic, antarctic, tropics, or individual
individual: # will only become relevant if location=individual
  # UPPER LEFT corner of bounding box
  lat0: 38.34
  lon0: -27.77
  # LOWER RIGHT corner of bounding box
  lat1: -40.09
  lon1: 68.55
  point_pad_deg: 2.0
polar:
  min_latitude: 60.0 # used for arctic
  max_latitude: -60.0 # used for antarctic

anomaly: false
difference: false # to era5
# only relevant if anomaly=true
baseline:
  start: "1981-01-01"
  end: "2010-12-31"

# colour grouping
group_years: 10
highlight_latest_year: true
highlight_previous_year: true
linewidth: 1.0
latest_linewidth: 2.4
previous_linewidth: 2.0
alpha: 0.9

figsize: [11, 6]
title: null
legend:
  loc: "lower center"
  inside_plot: false

special_outdir: null # options: string after outputs/yearly_cycle/{var} or null

