defaults:
# important to put _self_ first! (otherwise last)
  - _self_ # The _self_ entry determines the relative position of *this* config in the Defaults List.
  - datasets
  - variables
  - periods
  - plots@plots.soi: soi # load config/plots/soi.yaml and put its content under key plots.soi
  - plots@plots.global_mean: global_mean
  - plots@plots.anomalies: anomalies
  - plots@plots.bias_map: bias_map
  - plots@plots.location_timeseries: location_timeseries

# which plots to produce (must be names of REGISTRY in main.py)
run_plots: ["global_mean", "anomalies"] #, "soi", "anomalies", "bias_map", "soi_kde", "location_timeseries"]

# output behaviour
out:
  dir: outputs
  savefig: true
  dpi: 150
  overwrite: ask # options: ask, true, false

# conversion factors (K to deg C, scalar to percent)
# options: applies_to: [era5, model, both], op: [sub, add, mul, div]
# unit refers to the new unit after the conversion
conversions: 
  ta:  {op: "sub", value: 273.15, applies_to: "both", unit: "°C"}
  tas: {op: "sub", value: 273.15, applies_to: "both", unit: "°C"}
  tos: {op: "sub", value: 273.15, applies_to: "era5", unit: "°C"}  
  siconc: {op: "mul", value: 100, applies_to: "era5", unit: "%"}

freq_map:
  monthly: Amon
  daily: day
pattern: 
  monthly: "{var}_Amon_{modelname}_aimip_r*i1p1f1_gn_*.nc"
  daily:   "{var}_day_{modelname}_aimip_r*i1p1f1_gn_*.nc"

# members & mean
members: ["member1","member2","member3","member4","member5"]
include_ensemble_mean_as_member: true   # for bias / ENSO 

print_config: false

