datasets:

  era5:
    root: /work/bk1450/a270220/ERA5/regridded_to_1x1
    pattern: "ERA5_1x1_{var}_1978_2025.nc"

  models:
    forced_sst:
      root: /work/bk1450/a270220/cmorised_awm/forced_sst
      modelname: AWGsst0K
      proper_name: AW-Gen
      era5_offset_k: 0

    forced_sst_2k:
      root: /work/bk1450/a270220/cmorised_awm/forced_sst_2K
      modelname: AWGsst2K
      proper_name: AW-Gen +2K
      era5_offset_k: 2

    forced_sst_4k:
      root: /work/bk1450/a270220/cmorised_awm/forced_sst_4K
      modelname: AWGsst4K
      proper_name: AW-Gen +4K
      era5_offset_k: 4

    free_run_control:
      modelname: AWGfrc
      root: /work/bk1450/a270220/cmorised_awm/free_run_control
      proper_name: AW-Gen free-run
      era5_offset_k: 0

    free_run_prediction:
      modelname: AWGfr15
      root: /work/bk1450/a270220/cmorised_awm/free_run_prediction
      proper_name: AW-Gen free-run
      era5_offset_k: 0

    archesweather:
      modelname: ArchesWeather
      root: /work/bk1450/a270220/cmorised_awm/archesweather
      proper_name: AW
      era5_offset_k: 0